import type { Comment, Cook, Recipe } from './types';

export const cooks: Cook[] = [
  {
    id: 'mina',
    name: 'Mina Park',
    handle: '@minapark',
    init: 'MP',
    bg: 'linear-gradient(135deg,#ff8a4d,#e23a18)',
    blurb: 'Weeknight Japanese, fridge-first',
    bio: 'Tokyo-born, Brooklyn-based. I cook fast Japanese food with whatever’s in the fridge — no special trips.',
    followers: '214k',
    following: '182',
    likes: '4.1M',
    recipes: ['r1', 'r3b'],
  },
  {
    id: 'theo',
    name: 'Theo Okafor',
    handle: '@theocooks',
    init: 'TO',
    bg: 'linear-gradient(135deg,#f4a52c,#d8521e)',
    blurb: 'Live-fire & West-African roots',
    bio: 'Lagos to London. Everything tastes better over real flame. Big flavor, few pans.',
    followers: '308k',
    following: '96',
    likes: '6.8M',
    recipes: ['r2', 'r5'],
  },
  {
    id: 'lila',
    name: 'Lila Moreno',
    handle: '@lilamoreno',
    init: 'LM',
    bg: 'linear-gradient(135deg,#ff6f91,#d96a4a)',
    blurb: 'Pantry-first Mediterranean',
    bio: 'Sun-soaked plates from a tiny kitchen. Olive oil is a food group.',
    followers: '156k',
    following: '241',
    likes: '2.7M',
    recipes: ['r4', 'r8'],
  },
  {
    id: 'sora',
    name: 'Sora Lindqvist',
    handle: '@sorabakes',
    init: 'SL',
    bg: 'linear-gradient(135deg,#e8b04a,#b8922e)',
    blurb: 'Nordic bakes & slow mornings',
    bio: 'Cardamom, brown butter, and very good coffee. Baker by trade, napper by hobby.',
    followers: '92k',
    following: '120',
    likes: '1.5M',
    recipes: ['r6', 'r7'],
  },
  {
    id: 'dev',
    name: 'Dev Anand',
    handle: '@devheat',
    init: 'DA',
    bg: 'linear-gradient(135deg,#ff7a3d,#c23a1a)',
    blurb: 'Chili, chaat & maximum heat',
    bio: 'If it doesn’t make you sweat a little, why bother. Street food energy, home kitchen.',
    followers: '401k',
    following: '63',
    likes: '9.2M',
    recipes: ['r3', 'r3c'],
  },
];

export const recipes: Recipe[] = [
  {
    id: 'r1',
    title: 'Charred Miso Eggplant',
    cook: 'mina',
    cuisine: 'Japanese',
    time: '25 min',
    servings: 2,
    level: 'Easy',
    likeCount: '48.2k',
    dislikeCount: '210',
    shareCount: '3.1k',
    commentCount: '612',
    bg: 'linear-gradient(165deg,#2a160e,#b5471f)',
    ingredients: ['2 globe eggplants', '3 tbsp white miso', '1 tbsp mirin', '1 tbsp sake', 'Toasted sesame + scallion'],
    steps: [
      'Halve the eggplants and score the cut sides in a diamond pattern. Salt and rest 15 minutes.',
      'Whisk the miso, mirin and sake into a loose, paintable glaze.',
      'Sear cut-side down in a hot oiled pan until deeply caramelized, about 6 minutes.',
      'Flip, brush generously with glaze, and broil 3 minutes until bubbling and lacquered.',
      'Finish with toasted sesame and a shower of thin-sliced scallion.',
    ],
  },
  {
    id: 'r2',
    title: 'Saffron Seafood Rice',
    cook: 'theo',
    cuisine: 'Coastal',
    time: '45 min',
    servings: 4,
    level: 'Medium',
    likeCount: '91.7k',
    dislikeCount: '430',
    shareCount: '7.7k',
    commentCount: '1.4k',
    bg: 'linear-gradient(165deg,#3a1f06,#f4a52c)',
    ingredients: ['1½ cups bomba rice', 'Big pinch saffron', '300g mixed seafood', '1 onion, 3 garlic cloves', '4 cups warm stock'],
    steps: [
      'Bloom the saffron in a little warm stock and set aside.',
      'Soften onion and garlic in olive oil until jammy and sweet.',
      'Toast the rice for two minutes, then pour in the saffron stock.',
      'Simmer undisturbed until almost absorbed — resist the urge to stir.',
      'Nestle in the seafood, cover, and rest off the heat 5 minutes before serving.',
    ],
  },
  {
    id: 'r3',
    title: 'Midnight Chili Noodles',
    cook: 'dev',
    cuisine: 'Sichuan',
    time: '15 min',
    servings: 1,
    level: 'Easy',
    likeCount: '203k',
    dislikeCount: '1.1k',
    shareCount: '22k',
    commentCount: '3.1k',
    bg: 'linear-gradient(165deg,#1a1006,#c23a1a)',
    ingredients: ['1 nest wheat noodles', '2 tbsp chili crisp', '1 tbsp black vinegar', '1 tsp soy + sugar', 'Garlic, scallion, sesame'],
    steps: [
      'Boil the noodles until just past al dente, save a splash of the water.',
      'In a bowl, stir chili crisp, black vinegar, soy and sugar into a slick sauce.',
      'Sizzle minced garlic in hot oil and pour it over the sauce — it should crackle.',
      'Toss the hot noodles through with a spoon of pasta water to emulsify.',
      'Top with scallion and extra crisp. Eat immediately, standing up.',
    ],
  },
  {
    id: 'r4',
    title: 'Burrata & Heirloom Toast',
    cook: 'lila',
    cuisine: 'Mediterranean',
    time: '10 min',
    servings: 2,
    level: 'Easy',
    likeCount: '67.4k',
    dislikeCount: '180',
    shareCount: '5.2k',
    commentCount: '880',
    bg: 'linear-gradient(165deg,#3a1420,#d96a4a)',
    ingredients: ['2 thick slices sourdough', '1 ball burrata', '2 heirloom tomatoes', 'Basil, flaky salt', 'Good olive oil + honey'],
    steps: [
      'Grill the sourdough hard on both sides until it has real char.',
      'Rub the warm toast with a cut garlic clove.',
      'Tear the burrata over the top and let it slump into the bread.',
      'Pile on thick tomato slices, basil, flaky salt and pepper.',
      'Finish with olive oil and the smallest drizzle of honey.',
    ],
  },
  {
    id: 'r5',
    title: 'Smoked Short Rib Tacos',
    cook: 'theo',
    cuisine: 'Live-fire',
    time: '3 hr',
    servings: 6,
    level: 'Project',
    likeCount: '128k',
    dislikeCount: '520',
    shareCount: '14k',
    commentCount: '2.2k',
    bg: 'linear-gradient(165deg,#2a1208,#9c3d12)',
    ingredients: ['1.5kg beef short rib', 'Ancho + cumin rub', 'Corn tortillas', 'Pickled red onion', 'Lime, cilantro, salsa'],
    steps: [
      'Coat the ribs in the ancho-cumin rub and let them sit overnight.',
      'Smoke low and slow until the meat surrenders off the bone.',
      'Rest, then shred and toss through the rendered, smoky juices.',
      'Char the tortillas directly over the flame for a few seconds a side.',
      'Build with pickled onion, cilantro, a squeeze of lime and salsa.',
    ],
  },
  {
    id: 'r6',
    title: 'Pistachio Olive Oil Cake',
    cook: 'sora',
    cuisine: 'Bakes',
    time: '55 min',
    servings: 8,
    level: 'Medium',
    likeCount: '54.9k',
    dislikeCount: '140',
    shareCount: '6.0k',
    commentCount: '740',
    bg: 'linear-gradient(165deg,#2c2410,#b8922e)',
    ingredients: ['150g ground pistachio', '180ml olive oil', '3 eggs, 180g sugar', '120g flour + baking powder', 'Lemon zest + yogurt'],
    steps: [
      'Whisk eggs and sugar until pale, thick and tripled in volume.',
      'Stream in the olive oil slowly so it emulsifies into the batter.',
      'Fold in ground pistachio, flour, lemon zest and a spoon of yogurt.',
      'Bake at 170°C until the top springs back and smells nutty.',
      'Cool, then dust with icing sugar and extra chopped pistachio.',
    ],
  },
  {
    id: 'r7',
    title: 'Brown Butter Cardamom Buns',
    cook: 'sora',
    cuisine: 'Nordic',
    time: '2.5 hr',
    servings: 12,
    level: 'Project',
    likeCount: '88.1k',
    dislikeCount: '260',
    shareCount: '9.4k',
    commentCount: '1.9k',
    bg: 'linear-gradient(165deg,#3a2408,#d8901e)',
    ingredients: ['Enriched cardamom dough', '100g brown butter', 'Brown sugar + cinnamon', '1 egg for washing', 'Pearl sugar'],
    steps: [
      'Brown the butter until it smells of toffee and let it cool to spreadable.',
      'Roll the cardamom dough thin and spread with the brown butter sugar.',
      'Fold, slice and twist each bun into a knot — messy is good.',
      'Prove until pillowy, then brush with egg and scatter pearl sugar.',
      'Bake until deep gold and brush warm with a little syrup.',
    ],
  },
  {
    id: 'r8',
    title: 'Harissa Roast Chicken',
    cook: 'lila',
    cuisine: 'Mediterranean',
    time: '1 hr',
    servings: 4,
    level: 'Easy',
    likeCount: '112k',
    dislikeCount: '390',
    shareCount: '11k',
    commentCount: '1.6k',
    bg: 'linear-gradient(165deg,#3a1206,#d8521e)',
    ingredients: ['1 whole chicken', '3 tbsp rose harissa', 'Lemon + honey', 'Red onions, chickpeas', 'Yogurt to serve'],
    steps: [
      'Loosen the skin and push harissa, lemon and honey underneath.',
      'Tumble onions and chickpeas in the pan to roast in the drippings.',
      'Roast hot until the skin blisters and the harissa goes sticky.',
      'Rest the bird while the chickpeas crisp under the broiler.',
      'Carve over the chickpeas and spoon cold yogurt alongside.',
    ],
  },
  {
    id: 'r3b',
    title: 'Crispy Rice Omelette',
    cook: 'mina',
    cuisine: 'Japanese',
    time: '20 min',
    servings: 1,
    level: 'Easy',
    likeCount: '41k',
    dislikeCount: '120',
    shareCount: '2.4k',
    commentCount: '520',
    bg: 'linear-gradient(165deg,#2a1a0a,#e0762a)',
    ingredients: ['Day-old rice', '2 eggs', 'Soy + ketchup', 'Scallion', 'Butter'],
    steps: [
      'Fry the rice hard in butter until the bottom crackles.',
      'Season with soy and a little ketchup, then push to one side.',
      'Pour beaten egg into the pan and let it just set.',
      'Fold the egg over the rice like a blanket.',
      'Slick with more ketchup and a flurry of scallion.',
    ],
  },
  {
    id: 'r3c',
    title: 'Pani Puri Shots',
    cook: 'dev',
    cuisine: 'Chaat',
    time: '30 min',
    servings: 4,
    level: 'Medium',
    likeCount: '174k',
    dislikeCount: '900',
    shareCount: '19k',
    commentCount: '2.8k',
    bg: 'linear-gradient(165deg,#231406,#cf5a18)',
    ingredients: ['Crisp puri shells', 'Spiced potato + chickpea', 'Tamarind chutney', 'Mint coriander water', 'Sev + onion'],
    steps: [
      'Crack a small hole in each crisp puri shell.',
      'Spoon in spiced potato and chickpea filling.',
      'Top with sweet tamarind chutney.',
      'Flood with cold mint-coriander water just before eating.',
      'Finish with sev and onion and eat in one go.',
    ],
  },
];

/** Seed comments shown under every recipe. */
export const baseComments: Comment[] = [
  {
    name: 'noodlequeen',
    init: 'N',
    bg: 'linear-gradient(135deg,#ff8a4d,#e23a18)',
    text: 'made this last night and my whole apartment smelled incredible 🔥 saving forever',
    time: '2h',
    likes: '124',
  },
  {
    name: 'theo_cooks',
    init: 'T',
    bg: 'linear-gradient(135deg,#f4a52c,#d8521e)',
    text: 'the glaze tip at step 4 is everything. don’t skip the broil!',
    time: '4h',
    likes: '88',
  },
  {
    name: 'weeknightwin',
    init: 'W',
    bg: 'linear-gradient(135deg,#ff6f91,#d96a4a)',
    text: 'how spicy is this on a scale of 1-10? cooking for kids',
    time: '6h',
    likes: '31',
  },
  {
    name: 'sora.bakes',
    init: 'S',
    bg: 'linear-gradient(135deg,#e8b04a,#b8922e)',
    text: 'swapped in tofu and it still slapped. great base recipe ❤️',
    time: '8h',
    likes: '57',
  },
];

// Onboarding taste picks. Every label here MUST have keyword signals in the
// API's taste matcher (apps/api/src/services/taste.ts) so it influences the For
// You ranking — keep the two lists in sync when adding options.
export const tasteDefs: string[] = [
  // Cuisines
  'Japanese',
  'Chinese',
  'Korean',
  'Thai',
  'Vietnamese',
  'Indian',
  'Italian',
  'French',
  'Greek',
  'Mediterranean',
  'Mexican',
  'Caribbean',
  'Middle Eastern',
  'Soul food',
  'Southern BBQ',
  'American',
  // Diets & lifestyle
  'Vegetarian',
  'Vegan',
  'High protein',
  'Keto',
  'Gluten-free',
  'Halal',
  'Kosher',
  'Healthy',
  // Meals & styles
  'Breakfast',
  'Desserts',
  'Baking',
  'Street food',
  'Comfort food',
  'Spicy',
  'Quick & easy',
  'Low effort',
  'Meal prep',
  'Seafood',
  'Soups & stews',
  'Pasta',
  'Drinks',
];

export const trendChips: string[] = ['🔥 Trending', '15-min dinners', 'High protein', 'One pan', 'Sweet', 'Spicy'];

/** Masonry tile heights for the Discover grid, cycled by index. */
export const discoverHeights = ['188px', '230px', '200px', '250px', '210px', '240px', '196px', '224px'];

export const cookById = (id: string): Cook | undefined => cooks.find((c) => c.id === id);
export const recipeById = (id: string): Recipe | undefined => recipes.find((r) => r.id === id);
